from .version import __version__

from . import TheModels

from .TheModels.utils import pretrained_settings
from .TheModels.utils import model_names

# to support pretrainedmodels.__dict__['nasnetalarge']
# but depreciated
from .TheModels.fbresnet import fbresnet152
from .TheModels.cafferesnet import cafferesnet101
from .TheModels.bninception import bninception
from .TheModels.resnext import resnext101_32x4d
from .TheModels.resnext import resnext101_64x4d
from .TheModels.inceptionv4 import inceptionv4
from .TheModels.inceptionresnetv2 import inceptionresnetv2
from .TheModels.nasnet import nasnetalarge
from .TheModels.nasnet_mobile import nasnetamobile
from .TheModels.torchvision_models import alexnet
from .TheModels.densenet import densenet121
from .TheModels.densenet import densenet169
from .TheModels.densenet import densenet201
from .TheModels.densenet import densenet161
from .TheModels.torchvision_models import resnet18
from .TheModels.torchvision_models import resnet34
from .TheModels.torchvision_models import resnet50
from .TheModels.torchvision_models import resnet101
from .TheModels.torchvision_models import resnet152
from .TheModels.torchvision_models import inceptionv3
from .TheModels.torchvision_models import squeezenet1_0
from .TheModels.torchvision_models import squeezenet1_1
from .TheModels.torchvision_models import vgg11
from .TheModels.torchvision_models import vgg11_bn
from .TheModels.torchvision_models import vgg13
from .TheModels.torchvision_models import vgg13_bn
from .TheModels.torchvision_models import vgg16
from .TheModels.torchvision_models import vgg16_bn
from .TheModels.torchvision_models import vgg19_bn
from .TheModels.torchvision_models import vgg19
from .TheModels.dpn import dpn68
from .TheModels.dpn import dpn68b
from .TheModels.dpn import dpn92
from .TheModels.dpn import dpn98
from .TheModels.dpn import dpn131
from .TheModels.dpn import dpn107
from .TheModels.xception import xception
from .TheModels.senet import senet154
from .TheModels.senet import se_resnet50
from .TheModels.senet import se_resnet101
from .TheModels.senet import se_resnet152
from .TheModels.senet import se_resnext50_32x4d
from .TheModels.senet import se_resnext101_32x4d
from .TheModels.pnasnet import pnasnet5large
from .TheModels.polynet import polynet
from .MyPretrainModels import MyPretrainModels
